source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-remote-theme"
gem "jekyll-include-cache", "~> 0.2"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-seo-tag", "~> 2.8"
gem "webrick", "~> 1.8"
gem "jekyll-sass-converter", "~> 2.0"
